### ISSUE TITLE
no hal/nrf_xx.h found！

### ISSUE THREAD

**Issue by JiaDuo** [BabbleSim/ext_NRF52_hw_models#21]
I compile with “make everything -j 8” but get follow error： can you help me？thanks

`src/nrfx/hal/nrf_aar.c:9:10: fatal error: hal/nrf_aar.h: No such file or directory
    9 | #include "hal/nrf_aar.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
src/nrfx/hal/nrf_timer.c:8:10: fatal error: hal/nrf_timer.h: No such file or directory
    8 | #include "hal/nrf_timer.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: Entering directory '/home/zer0usn/other/bsim/components/ext_2G4_channel_NtNcable'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/zer0usn/other/bsim/components/ext_2G4_channel_NtNcable'
make[1]: *** [/home/zer0usn/other/bsim/components/common/make.lib_a.inc:27: /home/zer0usn/other/bsim/components/ext_NRF52_hw_models/src/nrfx/hal/nrf_aar.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [/home/zer0usn/other/bsim/components/common/make.lib_a.inc:27: /home/zer0usn/other/bsim/components/ext_NRF52_hw_models/src/nrfx/hal/nrf_timer.o] Error 1
src/nrfx/hal/nrf_ecb.c:8:10: fatal error: hal/nrf_ecb.h: No such file or directory
    8 | #include "hal/nrf_ecb.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: Entering directory '/home/zer0usn/other/bsim/components/ext_2G4_modem_magic'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/zer0usn/other/bsim/components/ext_2G4_modem_magic'
make[1]: *** [/home/zer0usn/other/bsim/components/common/make.lib_a.inc:27: /home/zer0usn/other/bsim/components/ext_NRF52_hw_models/src/nrfx/hal/nrf_ecb.o] Error 1
src/nrfx/hal/nrf_ppi.c:8:10: fatal error: hal/nrf_ppi.h: No such file or directory
    8 | #include "hal/nrf_ppi.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/home/zer0usn/other/bsim/components/common/make.lib_a.inc:27: /home/zer0usn/other/bsim/components/ext_NRF52_hw_models/src/nrfx/hal/nrf_ppi.o] Error 1
src/nrfx/hal/nrf_clock.c:8:10: fatal error: hal/nrf_clock.h: No such file or directory
    8 | #include "hal/nrf_clock.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [/home/zer0usn/other/bsim/components/common/make.lib_a.inc:27: /home/zer0usn/other/bsim/components/ext_NRF52_hw_models/src/nrfx/hal/nrf_clock.o] Error 1
make[1]: Leaving directory '/home/zer0usn/other/bsim/components/ext_NRF52_hw_models'
*** NOTE: ext_NRF52_hw_models could NOT be built, continuing ***
`

**Comment by aescolar** [comment]
It would seem NRFX_BASE is not pointing to the right path.
You need to point NRFX_BASE to the path where the Nordic HAL is.
So that, for example, `$NRFX_BASE/hal/nrf_aar.h` exists
