### ISSUE TITLE
Dynamic loading of libCryptov1.so causes problems with different folder architectures

### ISSUE THREAD

**Issue by alda-nordic** [BabbleSim/ext_NRF52_hw_models#34]
https://github.com/BabbleSim/ext_NRF52_hw_models/blob/57f0f656448d1ccbd3ebcd76a2bbfd1bc2157b25/src/HW_models/BLECrypt_if.c#L64

When instantiating the bsim devices from with internal commands, the .elf files are not in the /opt/bsim/bin repository.
Therefore, the crypto library cannot be found here "../lib/libCryptov1.so"

Would it be possible to use an environment variable, such as `BSIM_OUT_PATH`, instead of a dynamic path ?

**Comment by aescolar** [comment]
With this change https://github.com/BabbleSim/ext_NRF52_hw_models/commit/ff79a928c9252c73f1427465b816c6d42d3ea4ac
now the models will also search by LD_LIBRARY_PATH.

In any case, note that what the models expect is that the working directory is the bin/ folder of the simulator, but the executable does not necessarily need to be there. Meaning you can do the equivalent of 
`( cd ${BSIM_OUT_PATH}/bin/ ; ${ZEPHYR_BASE}/build/zephyr/zephyr.exe -nosim -RealEncryption=1 )`
(or whatever are the correct paths and executable name in your case)

**Comment by aescolar** [comment]
Closing as the models are now more flexible finding the library.
